org: mateoismael
service: api-geo-scraping

provider:
  name: aws
  runtime: python3.13
  # Default memory size for functions (default: 1024MB)
  memorySize: 1024
  timeout: 30
  iam:
    role: arn:aws:iam::111097882274:role/LabRole

functions:
  scrape_table:
    handler: scrap_table.lambda_handler
    package:
      include:
        - ./**
    events:
      - http:
          path: /scrape/sismos
          method: get
          cors: true
          integration: lambda

resources:
  Resources:
    SismosIGP:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: SismosIGP
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
